// src/Components/Edit/Edit.vue
<template>
  <div class="editWrapper">
      <p>{{task}}</p>
      <p>{{editedTask}}</p>
      <input v-model="editedTask.title"/>
      <input v-model="editedTask.price"/>
      <button @click="save">Save</button>
      <button @click="cancel">Cancel</button>
  </div>
</template>

<script>
import "./Edit.css";

export default {
  name: "edit",
  props: ["task"],
    data() {
    return {
      editedTask: {...this.task}
    };
  },
  methods: {
      save(){
          console.log('save')
          this.$emit("save", this.editedTask);
      },
      cancel(){
          this.$emit("cancel");
      }
  }
};
</script>

// src/Components/CardContainer/Components/Edit/index.tsx
import React from 'preact/compat';
import { Task } from 'types';
import styles from './edit.module.css';

type PropsTypes = Task & { onCancelClick: () => void };

const Edit: React.FC<PropsTypes> = (props: PropsTypes) => {
  const { title, type, price, onCancelClick } = props;
  return (
    <div className={styles.edit}>
      <input className={styles.title} value={title} />
      <input className={styles.type} value={type} />
      <input className={styles.price} value={price} />
      <button type="button" className={styles.cancel} onClick={onCancelClick}>
        CANCEL
      </button>
      <button type="button" className={styles.button}>
        OK
      </button>
    </div>
  );
};

export default Edit;
