// src/Components/Card/index.tsx
import React from 'preact/compat';
import { Task } from 'types';
import styles from './card.module.css';
import globalStyles from '../../global.module.css';

const Card: React.FC<Task> = (props: Task) => {
  const { ID, title, type, price } = props;
  return (
    <div className={styles.card}>
      <span className={`${globalStyles.blink} ${styles.title}`}>{title}</span>
      <span className={`${globalStyles.blink} ${styles.type}`}>{type}</span>
      <span className={`${globalStyles.blink} ${styles.price}`}>{price}</span>
      <button type="button" className={styles.edit}><span className={globalStyles.blink}>Edit</span></button>
      <button type="button" className={styles.button}>
        <span className={globalStyles.blink}>OK</span>
      </button>
    </div>
  );
};

export default Card;

// src/Components/Card/Card.vue
<template>
  <div class="wrapper">
    <p class="title">{{ task.title }}</p>
    <button class="complete">+</button>
    <button class="edit">⚙</button>
    <p class="description">{{ "task.descriptions" }}</p>
    <p v-if="task.price" class="price">{{ task.price }}</p>
    <progress
      v-if="progress"
      class="progress"
      :max="progress.max"
      :value="progress.value"
    />
  </div>
</template>

<script>
import "./Card.css";

export default {
  name: "card",
  props: ["task"],
  computed: {
    progress() {
      return { max: 100, value: 70 };
    },
  },
};
</script>
